export type ToolCategory =
  | "Video & Audio"
  | "Developer"
  | "Text"
  | "Image"
  | "Generators"
  | "Security"
  | "PDF";

export interface ToolAuthor {
  name: string;
  url?: string;
}

export interface ToolMeta {
  slug: string;
  name: string;
  description: string;
  category: ToolCategory;
  tags: string[];
  icon: string;
  /** True if this tool has a server-side API route under app/api/tools/<slug> */
  needsBackend: boolean;
  /** Name of a paid/premium product this tool replaces, if any */
  premiumAlternativeTo?: string;
  author: ToolAuthor;
}

export const tools: ToolMeta[] = [
  {
    slug: "youtube-playlist-length",
    name: "YouTube Playlist Length Calculator",
    description:
      "Get the total duration of any YouTube playlist, per-video breakdown, and watch time at faster playback speeds.",
    category: "Video & Audio",
    tags: ["youtube", "playlist", "duration", "video"],
    icon: "ListVideo",
    needsBackend: true,
    premiumAlternativeTo: "playlist length calculator extensions",
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "json-formatter",
    name: "JSON Formatter & Validator",
    description:
      "Format, minify, and validate JSON with clear error locations. Everything runs in your browser.",
    category: "Developer",
    tags: ["json", "formatter", "validator", "beautify"],
    icon: "Braces",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description:
      "Generate strong, random passwords and passphrases with custom length and character sets.",
    category: "Security",
    tags: ["password", "generator", "security", "random"],
    icon: "KeyRound",
    needsBackend: false,
    premiumAlternativeTo: "password manager generators",
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "word-counter",
    name: "Word & Character Counter",
    description:
      "Count words, characters, sentences, and paragraphs, plus estimated reading and speaking time.",
    category: "Text",
    tags: ["text", "word count", "characters", "reading time"],
    icon: "Type",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "color-converter",
    name: "Color Converter & Picker",
    description:
      "Convert colors between HEX, RGB, and HSL with a live picker and preview.",
    category: "Developer",
    tags: ["color", "hex", "rgb", "hsl", "picker"],
    icon: "Palette",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    description:
      "Turn any text or URL into a downloadable QR code, generated entirely on your device.",
    category: "Generators",
    tags: ["qr", "qr code", "generator"],
    icon: "QrCode",
    needsBackend: false,
    premiumAlternativeTo: "paid QR code generators",
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "image-compressor",
    name: "Image Compressor",
    description:
      "Shrink JPG, PNG, and WebP images right in your browser — nothing is uploaded anywhere.",
    category: "Image",
    tags: ["image", "compress", "resize", "optimize"],
    icon: "ImageDown",
    needsBackend: false,
    premiumAlternativeTo: "TinyPNG-style compressors",
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "base64-jwt-decoder",
    name: "Base64 & JWT Decoder",
    description:
      "Encode/decode Base64 strings and decode JWT headers & payloads to inspect their contents.",
    category: "Developer",
    tags: ["base64", "jwt", "decoder", "encode"],
    icon: "ScanText",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "url-encoder-decoder",
    name: "URL Encoder / Decoder",
    description:
      "Encode or decode URLs and query string components instantly, in your browser.",
    category: "Developer",
    tags: ["url", "encode", "decode", "uri"],
    icon: "Link2",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "uuid-generator",
    name: "UUID / ULID Generator",
    description:
      "Generate v4 UUIDs or sortable ULIDs, one at a time or in bulk.",
    category: "Developer",
    tags: ["uuid", "ulid", "generator", "id"],
    icon: "Fingerprint",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description:
      "Generate SHA-1, SHA-256, SHA-384, and SHA-512 hashes of any text, computed locally.",
    category: "Developer",
    tags: ["hash", "sha256", "sha1", "checksum"],
    icon: "Hash",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "timestamp-converter",
    name: "Timestamp Converter",
    description:
      "Convert between Unix epoch time and human-readable dates, in any timezone.",
    category: "Developer",
    tags: ["timestamp", "epoch", "unix", "date"],
    icon: "Timer",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    description:
      "Generate placeholder text by words, sentences, or paragraphs.",
    category: "Developer",
    tags: ["lorem ipsum", "placeholder", "generator", "text"],
    icon: "AlignLeft",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "http-status-lookup",
    name: "HTTP Status Code Lookup",
    description:
      "Look up what any HTTP status code means, with the full reference list searchable.",
    category: "Developer",
    tags: ["http", "status code", "reference"],
    icon: "Globe2",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "csv-json-converter",
    name: "CSV ⇄ JSON Converter",
    description:
      "Convert CSV to JSON or JSON to CSV, with automatic delimiter and type detection.",
    category: "Developer",
    tags: ["csv", "json", "converter"],
    icon: "Table2",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "diff-checker",
    name: "Diff Checker",
    description:
      "Compare two blocks of text and see exactly what changed, line by line.",
    category: "Developer",
    tags: ["diff", "compare", "text", "changes"],
    icon: "GitCompare",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    description:
      "Test regular expressions against sample text with live match highlighting and capture groups.",
    category: "Developer",
    tags: ["regex", "regular expression", "tester", "pattern"],
    icon: "Regex",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "markdown-previewer",
    name: "Markdown Previewer",
    description: "Write Markdown on one side and see the sanitized, rendered result on the other.",
    category: "Developer",
    tags: ["markdown", "preview", "editor"],
    icon: "FileText",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "cron-parser",
    name: "Cron Expression Explainer",
    description:
      "Turn a cron expression into plain English and see its next five scheduled run times.",
    category: "Developer",
    tags: ["cron", "schedule", "explainer"],
    icon: "CalendarClock",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "yaml-json-converter",
    name: "YAML ⇄ JSON Converter",
    description: "Convert YAML to JSON or JSON to YAML instantly, in your browser.",
    category: "Developer",
    tags: ["yaml", "json", "converter"],
    icon: "FileCode2",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "code-formatter",
    name: "Code Formatter",
    description: "Beautify or minify JavaScript, CSS, and HTML snippets.",
    category: "Developer",
    tags: ["formatter", "beautify", "minify", "css", "html", "javascript"],
    icon: "Wand2",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "curl-to-fetch",
    name: "curl → fetch Converter",
    description: "Paste a curl command and get an equivalent JavaScript fetch() snippet.",
    category: "Developer",
    tags: ["curl", "fetch", "converter", "snippet"],
    icon: "Terminal",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    description:
      "Convert text between camelCase, snake_case, kebab-case, Title Case, and more.",
    category: "Text",
    tags: ["case", "camelcase", "snake_case", "converter"],
    icon: "CaseSensitive",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "slug-generator",
    name: "Slug Generator",
    description: "Turn any title into a clean, URL-safe slug.",
    category: "Text",
    tags: ["slug", "url", "seo", "generator"],
    icon: "Slash",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "find-replace",
    name: "Find & Replace",
    description: "Find and replace text across a large block, with optional regex support.",
    category: "Text",
    tags: ["find", "replace", "regex", "text"],
    icon: "Replace",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "line-tools",
    name: "Duplicate Line Remover & Sorter",
    description: "Remove duplicate or blank lines and sort a list alphabetically.",
    category: "Text",
    tags: ["duplicate", "lines", "sort", "dedupe"],
    icon: "Rows3",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "text-to-speech",
    name: "Text to Speech",
    description: "Have any text read aloud using your browser's built-in voices.",
    category: "Text",
    tags: ["text to speech", "tts", "accessibility", "audio"],
    icon: "Volume2",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "image-format-converter",
    name: "Image Format Converter",
    description: "Convert images between PNG, JPEG, and WebP, right in your browser.",
    category: "Image",
    tags: ["image", "convert", "png", "jpeg", "webp"],
    icon: "FileImage",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    description: "Resize an image to exact dimensions, with an optional locked aspect ratio.",
    category: "Image",
    tags: ["image", "resize", "dimensions"],
    icon: "Maximize2",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "favicon-generator",
    name: "Favicon Generator",
    description: "Turn one image into a full set of favicon sizes, bundled as a zip.",
    category: "Image",
    tags: ["favicon", "icon", "generator"],
    icon: "AppWindow",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "exif-viewer",
    name: "EXIF Viewer & Remover",
    description: "See a photo's embedded metadata, or strip it out before sharing.",
    category: "Image",
    tags: ["exif", "metadata", "privacy", "photo"],
    icon: "Info",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "meme-generator",
    name: "Meme Generator",
    description: "Add classic top and bottom captions to any image and download it.",
    category: "Image",
    tags: ["meme", "generator", "caption", "image"],
    icon: "Smile",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "image-base64-converter",
    name: "Image ⇄ Base64 Converter",
    description: "Convert an image file to a base64 data URL, or preview a base64 string as an image.",
    category: "Image",
    tags: ["image", "base64", "data url", "converter"],
    icon: "Code",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "collage-maker",
    name: "Collage / Grid Maker",
    description: "Arrange multiple photos into a single grid collage and download it as one image.",
    category: "Image",
    tags: ["collage", "grid", "photos", "layout"],
    icon: "LayoutGrid",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "barcode-generator",
    name: "Barcode Generator",
    description: "Generate CODE128, EAN-13, UPC, and other barcode formats as a downloadable image.",
    category: "Generators",
    tags: ["barcode", "generator", "ean13", "code128"],
    icon: "Barcode",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "random-picker",
    name: "Random Name Picker & Team Splitter",
    description: "Paste a list of names to pick a random winner or split everyone into fair teams.",
    category: "Generators",
    tags: ["random", "picker", "teams", "raffle"],
    icon: "Users",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "fake-data-generator",
    name: "Fake Data Generator",
    description: "Generate realistic-looking fake names, emails, addresses, and more for testing.",
    category: "Generators",
    tags: ["fake data", "mock", "test data", "generator"],
    icon: "Database",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "invoice-generator",
    name: "Invoice Generator",
    description: "Fill in a simple invoice and download it as a PDF — no account needed.",
    category: "Generators",
    tags: ["invoice", "pdf", "billing", "generator"],
    icon: "Receipt",
    needsBackend: false,
    premiumAlternativeTo: "paid invoicing tools",
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "resume-builder",
    name: "Resume / CV Builder",
    description: "Build a clean, one-page resume and export it straight to PDF.",
    category: "Generators",
    tags: ["resume", "cv", "pdf", "builder"],
    icon: "FileUser",
    needsBackend: false,
    premiumAlternativeTo: "paid resume builders",
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "wheel-of-names",
    name: "Wheel of Names",
    description: "Spin a wheel to randomly pick from a list of names or options.",
    category: "Generators",
    tags: ["wheel", "random", "picker", "spinner"],
    icon: "CircleDot",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "dice-coin-flip",
    name: "Dice Roller & Coin Flip",
    description: "Roll one or more dice, or flip a coin, with a satisfying bit of animation.",
    category: "Generators",
    tags: ["dice", "coin flip", "random", "game"],
    icon: "Dices",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "password-strength-checker",
    name: "Password Strength Checker",
    description: "See how strong a password is, with an estimated crack time and concrete fixes.",
    category: "Security",
    tags: ["password", "strength", "entropy", "security"],
    icon: "ShieldCheck",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "totp-generator",
    name: "2FA / TOTP Code Generator",
    description: "Generate live 6-digit authenticator codes from a base32 secret key.",
    category: "Security",
    tags: ["2fa", "totp", "authenticator", "mfa"],
    icon: "Lock",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "password-breach-checker",
    name: "Password Breach Checker",
    description: "Check if a password has appeared in a known data breach, without ever sending it anywhere.",
    category: "Security",
    tags: ["password", "breach", "pwned", "security"],
    icon: "ShieldAlert",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "ssl-certificate-checker",
    name: "SSL Certificate Checker",
    description: "Look up a domain's recent SSL/TLS certificates via public certificate transparency logs.",
    category: "Security",
    tags: ["ssl", "tls", "certificate", "https"],
    icon: "ScanSearch",
    needsBackend: true,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "pdf-merge",
    name: "Merge PDF",
    description: "Combine multiple PDF files into one, in the order you choose.",
    category: "PDF",
    tags: ["pdf", "merge", "combine"],
    icon: "FilePlus2",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "pdf-split",
    name: "Split PDF",
    description: "Extract a page range from a PDF, or split it into individual pages.",
    category: "PDF",
    tags: ["pdf", "split", "extract", "pages"],
    icon: "Scissors",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "pdf-compress",
    name: "Compress PDF",
    description: "Strip metadata and repack a PDF's internal structure to shave off some size.",
    category: "PDF",
    tags: ["pdf", "compress", "optimize"],
    icon: "FileMinus2",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "pdf-watermark",
    name: "Watermark PDF",
    description: "Stamp a diagonal text watermark across every page of a PDF.",
    category: "PDF",
    tags: ["pdf", "watermark", "stamp"],
    icon: "Stamp",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "images-to-pdf",
    name: "Images to PDF",
    description: "Combine one or more images into a single PDF, reorderable before export.",
    category: "PDF",
    tags: ["images", "pdf", "convert"],
    icon: "Images",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
  {
    slug: "pdf-to-images",
    name: "PDF to Images",
    description: "Render every page of a PDF as a downloadable PNG image.",
    category: "PDF",
    tags: ["pdf", "images", "convert", "render"],
    icon: "FileOutput",
    needsBackend: false,
    author: { name: "Toolbox", url: "https://github.com/masabinhok" },
  },
];

export const categories = Array.from(
  new Set(tools.map((t) => t.category))
) as ToolCategory[];

export function getToolBySlug(slug: string): ToolMeta | undefined {
  return tools.find((t) => t.slug === slug);
}
